spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/boot8am
    username: root
    password: Jagrutikp@98
    
  jpa: 
      show_sql: true
      database-platform: org.hibernate.dialect.MySQL8Dialect
      hibernate:
       ddl-auto: update
       